#!/usr/bin/env python3
"""Embed Skills/xcforge into the xcforge binary.

Writes Sources/XCForgeKit/Skill/EmbeddedSkill.swift so `xcforge skill install`
can write the skill without the repo checkout. Run it after editing anything
under Skills/xcforge; SkillBundleTests fails while the two differ.

    python3 scripts/embed-skill.py
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL_DIR = ROOT / "Skills" / "xcforge"
OUT = ROOT / "Sources" / "XCForgeKit" / "Skill" / "EmbeddedSkill.swift"


def delimiter_hashes(text: str) -> str:
    """Fewest #s so the text can't close the raw string or interpolate."""
    n = 1
    while ('"""' + "#" * n) in text or ("\\" + "#" * n) in text:
        n += 1
    return "#" * n


def literal(text: str) -> str:
    hashes = delimiter_hashes(text)
    # The line break just before the closing delimiter is not part of a
    # multi-line literal, so one extra break keeps the text byte-for-byte.
    return f'{hashes}"""\n{text}\n"""{hashes}'


def main() -> int:
    files = sorted(
        p for p in SKILL_DIR.rglob("*") if p.is_file() and not p.name.startswith(".")
    )
    if not files:
        print(f"no files under {SKILL_DIR}", file=sys.stderr)
        return 1
    out = [
        "// swift-format-ignore-file",
        "// Generated by scripts/embed-skill.py from Skills/xcforge. Do not edit by hand:",
        "// change Skills/xcforge, then run `python3 scripts/embed-skill.py`.",
        "",
        "extension SkillBundle {",
        "  static let embeddedFiles: [SkillFile] = [",
    ]
    for path in files:
        rel = path.relative_to(SKILL_DIR).as_posix()
        text = path.read_text(encoding="utf-8")
        out.append(f'    SkillFile(path: "{rel}", contents: {literal(text)}),')
    out += ["  ]", "}", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(files)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
